language: python

matrix:
  include:
    - python: pypy
      env: TOXENV=pypy
    - python: 3.5
      env: TOXENV=py35
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38

env:
  - TOXENV=py27
  - TOXENV=py36
  - TOXENV=cover
  - TOXENV=flake8

install:
  - travis_retry pip install tox==3.13.2

script:
  - travis_retry tox

git:
  depth: 1

notifications:
  email:
    - chad@hutchins.house
